### ISSUE TITLE
Installer not working

### ISSUE THREAD

**Issue by DiegoCardona** [laromicas/datoso#1]
It seems like the min python version is 3.10 and some libraries are not found and not included with the installer.

![image](https://user-images.githubusercontent.com/4804680/234714644-0a160340-f09e-4241-b382-90e7b9c80aec.png)

**Comment by laromicas** [comment]
Hi, the minimum python version for datoso (as is a recent project) is 3.10, I invite you to upgrade your python version to 3.11 that offers a lot of improvements.
https://pythontest.com/python/installing-python-3-11/
